# Generated by scripts/publish-package-repos.js — do not edit by hand.
cask "myhomegames-server" do
  version "1.2.0"

  if Hardware::CPU.arm?
    sha256 "14e4b0a74d41d63a394a3c4f15e16cc8df2f7385d50155f1c08071cb5119d676"
    url "https://github.com/myhomegames/myhomegames-server/releases/download/1.2.0/MyHomeGames-1.2.0-mac-arm64.pkg"
  else
    sha256 "3627fadf7962d2f9be2161b3d24c10bfc5eed2f96f4fea8b95244b334eb38d35"
    url "https://github.com/myhomegames/myhomegames-server/releases/download/1.2.0/MyHomeGames-1.2.0-mac-x64.pkg"
  end

  name "MyHomeGames Server"
  desc "Self-hosted game library server"
  homepage "https://myhomegames.vige.it"

  pkg "MyHomeGames-#{version}-mac-#{Hardware::CPU.arm? ? 'arm64' : 'x64'}.pkg"

  uninstall pkgutil: "com.myhomegames.server"
end
