# Generated by scripts/publish-package-repos.js — do not edit by hand.
cask "myhomegames-server" do
  version "1.1.2"

  if Hardware::CPU.arm?
    sha256 "13863958a45079d4999c52fbc818a997c627397e15a4ecde905ddf7c2581089f"
    url "https://github.com/myhomegames/myhomegames-server/releases/download/1.1.2/MyHomeGames-1.1.2-mac-arm64.pkg"
  else
    sha256 "8b9a38483fada5a23f115a27b654130e467320667ba745f16d2384184ad18590"
    url "https://github.com/myhomegames/myhomegames-server/releases/download/1.1.2/MyHomeGames-1.1.2-mac-x64.pkg"
  end

  name "MyHomeGames Server"
  desc "Self-hosted game library server"
  homepage "https://myhomegames.vige.it"

  pkg "MyHomeGames-#{version}-mac-#{Hardware::CPU.arm? ? 'arm64' : 'x64'}.pkg"

  uninstall pkgutil: "com.myhomegames.server"
end
