# Generated by scripts/publish-package-repos.js — do not edit by hand.
cask "myhomegames-server" do
  version "1.2.4"

  if Hardware::CPU.arm?
    sha256 "43181fbe2cc61d7d104db5e779c31317a005c4aeee3616963e5e893e37e2b752"
    url "https://github.com/myhomegames/myhomegames-server/releases/download/1.2.4/MyHomeGames-1.2.4-mac-arm64.pkg"
  else
    sha256 "7673ee45faadd40dad68fbce8d310a1baae540b52e0f8166b6ff1ea981a1b7be"
    url "https://github.com/myhomegames/myhomegames-server/releases/download/1.2.4/MyHomeGames-1.2.4-mac-x64.pkg"
  end

  name "MyHomeGames Server"
  desc "Self-hosted game library server"
  homepage "https://myhomegames.vige.it"

  pkg "MyHomeGames-#{version}-mac-#{Hardware::CPU.arm? ? 'arm64' : 'x64'}.pkg"

  uninstall pkgutil: "com.myhomegames.server"
end
